version: "3"

services:
  postgres:
    image: "postgres:11"
    container_name: "realworld_postgres"
    ports:
      - "54320:5432"
    volumes:
      - ./.docker/data:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=userpassword
    networks:
      - drash-app-network

  drash:
    container_name: realworld_drash
    image: tjozsa/conduit
    volumes:
      - ./src:/var/www/src
    working_dir: /var/www/src
    ports:
      - "1667:1667"
    networks:
      - drash-app-network

networks:
  drash-app-network:
    driver: bridge
